# Generated by Django 3.0.3 on 2020-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('addres', models.CharField(max_length=100, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('exam', models.CharField(max_length=100, verbose_name='Direccion')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('image', models.ImageField(upload_to='', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
            },
        ),
    ]
