# Generated by Django 3.0.3 on 2020-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200512_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
