# Generated by Django 3.0.3 on 2020-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_examenes_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='exam',
            field=models.IntegerField(choices=[('glucosa', 'glucosa'), ('vih', 'vih'), ('cuadro hematico', 'cuadro hematico')], max_length=200, verbose_name='Tipo de examen'),
        ),
    ]
