# Generated by Django 3.0.3 on 2020-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200521_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='exam',
            field=models.CharField(choices=[('glucosa', 'glucosa'), ('vih', 'vih'), ('cuadro hematico', 'cuadro hematico')], max_length=200, verbose_name='Tipo de examen'),
        ),
    ]
